# Generated by Django 3.0.11 on 2020-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, max_length=500, verbose_name='Short Bio'),
        ),
    ]
