# Generated by Django 3.0.11 on 2021-01-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201208_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs_of_interest',
            field=models.CharField(blank=True, max_length=250, verbose_name='Job Titles of Interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, max_length=250, verbose_name='Skills'),
        ),
    ]
