# Generated by Django 3.0.11 on 2021-01-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_text',
            new_name='job_clean_text',
        ),
        migrations.AddField(
            model_name='job',
            name='job_raw_text',
            field=models.CharField(default='null', max_length=250000),
        ),
    ]
